// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ9yMg33kH8KHXUtHyzMLqYW3AXIU06Kw',
    appId: '1:316587986970:web:3d17e8803c1e74c553c1a3',
    messagingSenderId: '316587986970',
    projectId: 'ap-202306c',
    authDomain: 'ap-202306c.firebaseapp.com',
    storageBucket: 'ap-202306c.firebasestorage.app',
    measurementId: 'G-B325DQGWDF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZvfylyjCqH9fAb8fxsHjqQHrHI8gapPE',
    appId: '1:316587986970:android:db6510668c8ba95353c1a3',
    messagingSenderId: '316587986970',
    projectId: 'ap-202306c',
    storageBucket: 'ap-202306c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGG322u-_mTts8zGXXu7vJ36hl4uk8zQg',
    appId: '1:316587986970:ios:09a277d7fac5e48653c1a3',
    messagingSenderId: '316587986970',
    projectId: 'ap-202306c',
    storageBucket: 'ap-202306c.firebasestorage.app',
    iosBundleId: 'com.example.flutterProjectSixc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGG322u-_mTts8zGXXu7vJ36hl4uk8zQg',
    appId: '1:316587986970:ios:09a277d7fac5e48653c1a3',
    messagingSenderId: '316587986970',
    projectId: 'ap-202306c',
    storageBucket: 'ap-202306c.firebasestorage.app',
    iosBundleId: 'com.example.flutterProjectSixc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZ9yMg33kH8KHXUtHyzMLqYW3AXIU06Kw',
    appId: '1:316587986970:web:52a02d4a2e95a0b653c1a3',
    messagingSenderId: '316587986970',
    projectId: 'ap-202306c',
    authDomain: 'ap-202306c.firebaseapp.com',
    storageBucket: 'ap-202306c.firebasestorage.app',
    measurementId: 'G-QB1B7004DP',
  );
}
